version: '3'

services:
  # --- Database Services ---
  source_postgres:
    image: postgres:15
    ports:
      - '5433:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - source_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  destination_postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - dest_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Airflow Services ---
  airflow-webserver:
    build: ./airflow
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-metadata:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDqPgmJbboyMkDzhp0901afJ70=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock # Allow Airflow to spawn sibling containers
    networks:
      - elt_network

  airflow-scheduler:
    build: ./airflow
    command: scheduler
    depends_on:
      - airflow-metadata
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-metadata:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDqPgmJbboyMkDzhp0901afJ70=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elt_network

  airflow-metadata:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - elt_network

  # --- ELT & DBT Images (Built for Airflow to use) ---
  elt_script_image:
    build:
      context: ./elt_script
      dockerfile: Dockerfile
    image: elt_script_v1:latest
    networks:
      - elt_network
    command: ["echo", "Image built successfully"] 

  dbt_image:
    build:
      context: ./elt_database
      dockerfile: Dockerfile
    image: dbt_custom_v1:latest
    networks:
      - elt_network
    command: ["echo", "Image built successfully"]

networks:
  elt_network:
    driver: bridge

volumes:
  source_pg_data:
  dest_pg_data:
